import pynini
import regex
from transformers import NllbTokenizer, SPIECE_UNDERLINE

from pywrapfst import SymbolTableView

fst = pynini.Fst.read('analyzeCuzco.windows.fst')
input_symbols: SymbolTableView = fst.input_symbols()
output_symbols: SymbolTableView = fst.output_symbols()

EPSILON_IDX =  0
SMALLEST_CHUNK_FOR_FST = 1

TOKEN_RE = regex.compile(r"[\p{L}']+|[^\s\p{L}']+|\s+")

# With our current dataset there is only one FST produced token that conflicts with the original vocabulary.
COLLISION_PREFIX = '⩲'
_COLLISIONS_MAP = {
    'SP': f'{COLLISION_PREFIX}SP'
}

SPECIAL_PREFIX_TAGS = [
    f'{SPIECE_UNDERLINE}=',
    f'{SPIECE_UNDERLINE}{COLLISION_PREFIX}',
    '=',
    '+',
    COLLISION_PREFIX,
    SPIECE_UNDERLINE
]

def _fix_collision(morpheme: str) -> str:
    if morpheme in _COLLISIONS_MAP:
        return _COLLISIONS_MAP[morpheme]
    return morpheme

def run_fst(word: str) -> list[str] | None:
    '''Runs fst and returns the list of morphemes or None if the fst doesn't recognize it.'''
    # build acceptor over the FST's symbol table, one char per arc
    try:
        acceptor = pynini.accep(' '.join(word), token_type=input_symbols)
    except pynini.FstStringCompilationError:
        return None
    
    lattice = pynini.shortestpath(acceptor @ fst)

    if lattice.num_states() == 0:
        return None
    
    morphemes: list[str] = []
    state = lattice.start()

    while True:
        if state == -1:
            raise ValueError(f'running fst on word: {word} caused an error to arise')
        arc = next(iter(lattice.arcs(state)), None)
        if arc is None:
            break
        if arc.olabel != EPSILON_IDX:
            sym = output_symbols.find(arc.olabel)
            if len(sym) > 0:
                morphemes.append(_fix_collision(sym))
        state = arc.nextstate
    return morphemes

def segment_surface(word: str) -> list[tuple[str, str]] | None:
    '''
    Segment a word along its morpheme boundaries while preserving the exact surface characters.

    Unlike run_fst (which reads the FST's normalized output tape), this reads the INPUT (surface)
    tape and only uses the output symbols to mark boundaries, so the original spelling is kept and
    concatenating the segments reproduces the word exactly. Returns a list of (marker, surface)
    pairs, or None if the FST doesn't recognize the word. marker is '=' (root/word-initial) or
    '+' (suffix).
    '''
    try:
        # The FST's input alphabet is single characters, so space-separate the word
        # ("wasi" -> "w a s i"); otherwise accep looks up "wasi" as one symbol and rejects it.
        acceptor = pynini.accep(' '.join(word), token_type=input_symbols)
    except pynini.FstStringCompilationError:
        return None

    # acceptor @ fst yields every analysis of the word; shortestpath keeps the lowest-cost one.
    best_parse = pynini.shortestpath(acceptor @ fst)
    if best_parse.num_states() == 0:
        return None

    segs: list[list[str]] = []   # each entry: [marker, surface_substring]
    leading = ''                 # chars consumed before the first morpheme symbol (rare)
    state = best_parse.start()
    while state != -1:
        arc = next(iter(best_parse.arcs(state)), None)  # arcs() is a lazy iterator; None at the final state
        if arc is None:
            break
        ich = input_symbols.find(arc.ilabel) if arc.ilabel != EPSILON_IDX else ''

        if arc.olabel != EPSILON_IDX:
            # Symbol-first rule: an output symbol marks a new morpheme and rides on the arc
            # carrying that morpheme's first surface char -> start a new segment.
            osym = output_symbols.find(arc.olabel)
            marker = '+' if osym.startswith('+') else '='
            segs.append([marker, leading + ich])
            leading = ''
        elif segs:
            segs[-1][1] += ich          # no symbol: char continues the current morpheme
        else:
            leading += ich              # no morpheme open yet; hold until the first symbol
        state = arc.nextstate

    if leading and segs:                # flush trailing chars emitted after the last symbol
        segs[-1][1] += leading
    return [(m, s) for m, s in segs]

def get_unique_fst_morphemes(text: str) -> set[str]:
    '''Returns all morpheme types generated by the fst on the given text.'''
    text = text.replace("’", "'")
    morphemes: set[str] = set()

    for match in TOKEN_RE.finditer(text):
        tok = match.group(0)

        # Skip whitespace and pure punctuation
        if tok.isspace() or not any(c.isalpha() for c in tok):
            continue

        # Strip outer apostrophes
        lead_len = len(tok) - len(tok.lstrip("'"))
        trail_len = len(tok) - len(tok.rstrip("'"))
        core = tok[lead_len : len(tok) - trail_len] if trail_len else tok[lead_len:]

        if len(core) <= SMALLEST_CHUNK_FOR_FST:
            continue

        result = run_fst(core)
        if result is not None:
            morphemes.update(result)

    return morphemes

def encode_text(text: str, nllb_tokenizer: NllbTokenizer) -> list[str]:
    '''
    Encodes the text using the fst and falls back to the nllb_tokenizer for text that isn't words or
    text that the fst doesn't recognize. Each whitespace separated chunk becomes a single piece
    with its morphemes and punctuation concatenated together.
    '''
    text = text.replace("’", "'")
    pieces: list[str] = []

    for chunk in text.split():
        first_token_is_fst = False
        chunk_pieces: list[str] = []

        for match in TOKEN_RE.finditer(chunk):
            tok = match.group(0)

            # if tok.isspace():
            #     continue

            if not any(c.isalpha() for c in tok):
                chunk_pieces.append(tok)
                continue

            lead_len = len(tok) - len(tok.lstrip("'"))
            trail_len = len(tok) - len(tok.rstrip("'"))
            core = tok[lead_len: len(tok) - trail_len] if trail_len else tok[lead_len:]

            if lead_len > 0:
                chunk_pieces.append(tok[:lead_len])

            if len(core) > SMALLEST_CHUNK_FOR_FST:
                morphemes = run_fst(core)
                if morphemes is not None:
                    if len(chunk_pieces) == 0:
                            first_token_is_fst = True
                    chunk_pieces.extend(morphemes)
                else:
                    chunk_pieces.append(core)
            elif len(core) > 0:
                    chunk_pieces.append(core)

            if trail_len > 0:
                chunk_pieces.append(tok[-trail_len:])

        if len(chunk_pieces) > 0:
            piece = ''.join(chunk_pieces)
            if first_token_is_fst:
                piece = SPIECE_UNDERLINE + piece
            pieces.append(piece)

    return pieces